### ISSUE TITLE
How to execute code?

### ISSUE THREAD

**Issue by maryampashmi** [DanWahlin/CustomerManager#22]
Honestly this definition is not clear at all . It was good if somebody who know how we can execute this code take a video of all this instructions in order to be clear. I spent near 2 hours, after having lots of error i change my opinion to continue with it. 
What is happen if somebody is not familiar with mongodb. so how we can continue all this steps and so on.

**Comment by DanWahlin** [comment]
Sorry to hear you had some challenges with it. This is a free sample app though (not a course or tutorial) so the assumption is that people wanting to run the sample work with the underlying technologies that the sample uses. That's especially true with this particular sample since it shows a more advanced example of using Angular's routing functionality. My CustomerManagerStandard project is a simplified version of this project but still uses the same setup shown in the readme.

There are two options provided (Node.js/MongoDB and Visual Studio/C#/SQL Server) as mentioned in the readme and the easiest option if you just want to see the Angular part working is to download Visual Studio 2013 Community edition (free) and load the project as shown in the readme. That's only going to work if you're running Windows of course. If you're on Mac or Linux then you'll have to go with the Node.js/MongoDB option. 

While I've had 100s of people run it successfully I agree there's definitely some setup work required if you don't already have MongoDB in place so I'd recommend first getting MongoDB going. You can find instructions on that here for any OS:

http://docs.mongodb.org/manual/installation/

Once that's setup you an go through the readme steps that are shown to get the application going.

**Comment by maryampashmi** [comment]
Thank you for your answer. 
I got answer with visual basic as it is so simple . Actually i would like to try a little bit work on configuration of mongodb in you code. Any way, if you can do in feature and go more deeply through your code will be more interesting especially for beginners. ;)
